ali_image_path: "/home/u2023111315/ai_challenger_caption_train_20170902/caption_train_images_20170902/"
ali_image_path_label_file: "/home/u2023111315/ai_challenger_caption_train_20170902/caption_train_annotations_20170902.json"

coco_image_path: "/home/u2023111315/train2017/"
coco_image_path_label_file1: "/home/u2023111315/Basic-Vision-Language-Model/data/complex_reasoning_77k.json"
coco_image_path_label_file2: "/home/u2023111315/Basic-Vision-Language-Model/data/detail_23k.json"

output_image_map: "/home/u2023111315/Basic-Vision-Language-Model/data/image_map_b.json"
output_captions: "/home/u2023111315/Basic-Vision-Language-Model/data/captions_b.json"
